name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Set environment variable
      run: echo "ENV_SECRET=${{ secrets.ENV_SERVER }}" >> $GITHUB_ENV
    - name: Display environment variable
      run: echo "Secret is $ENV_SECRET"
