name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Display environment
      run: echo secret "${{ github.event.inputs.environment }}" | sed 's/./& /g'
    - name: Display environment variable
      run: echo secret "${{secrets.ENV_SERVER }}" | sed 's/./& /g'
    - name: Display environment variable2
      run: echo variables "${{ vars.BACKEND }}"
